title: PixelZerg
description: Hi, Iâ€™m Abhinav. Fascinated by Computer Science. Experiment with Python/C#/JS for fun. Have a tendency to get engrossed in interesting stuff. Welcome to me being me.

author:
  name:    Abhinav Bhandari
  twitter: pixelzerg
  github:  pixelzerg
  email:   pixelzerg@gmail.com

baseurl: ""
url: "http://pixelzerg.github.io"
gh: "http://github.com/pixelzerg"

defaultimage: "/assets/images/default.jpg"

permalink: /:categories/:title/

# seo
social:
  name: Abhinav Bhandari
  links:
    - https://twitter.com/pixelzerg
    - https://github.com/pixelzerg

# Build stuff:
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
sass:
  sass_dir: _sass
  style: compressed

# collections:
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"